version: '2'
services:
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null

  kyc-server:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    image: boomerang/node-server-meet-assist:latest
    ports:
      - "3000:3000"
    network_mode: "host"
    environment:
      DB_HOST: "localhost"
      DB_PORT: "27017"



